version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5001"  # Adjust the ports as needed
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
    volumes:
      - .:/app  # Mount your application code into the container

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=flaskpostgre